version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome
    docker:
      - image: "cypress/browsers:node12.14.1-chrome86
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 1
          group: 1 machines
