version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
  jobs:
      # install dependencies first (on 1 machine)
      - cypress/install
      # now run tests
      - cypress/run:
          executor: cypress/browsers-chrome69
          browser: chrome
          # give this job a custom name for clarity
          name: 'end-to-end tests'
          requires:
            # use previously installed dependencies
            # to avoid installing them on each machine running tests
            - cypress/install
          record: true # record results to Cypress Dashboard
#     jobs:
#       - cypress/install
#       - cypress/run:
#           executor: cypress/browsers-chrome69
#           browser: chrome

#           requires:
#             - cypress/install
#           record: true
#           parallel: true
#           parallelism: 1
#           group: 1 machines
